### ISSUE TITLE
stop showing autocomplete after write a close brace(}), semi colon(;) and close parenthesis

### ISSUE THREAD

**Issue by OguzhanE** [TypeStrong/atom-typescript#268] opened 2015-04-18 14:13 UTC
that's really annoying.
![Imgur](http://i.imgur.com/6m63tX8.gif)

**Comment by basarat** [comment] 2015-04-18 22:35
Duplicate of https://github.com/TypeStrong/atom-typescript/issues/141 

Current workaround is to not bind *confirm* to enter and just use tab completions. Having said that I'll see if I can tackle #141 again (no easy answer here ... as it seems I'll need to switch off completions in this case completely which means *you will not be able to* get autocomplete if you want to write code in a single line)

**Closed by basarat** 2015-04-18 22:35 UTC
Labels: duplicate
