### ISSUE TITLE
atom-typescript installed but no autocomplete, no format code, only get the typescript status bar

### ISSUE THREAD

**Issue by samuelneff** [TypeStrong/atom-typescript#549] opened 2015-08-30 18:55 UTC
I installed atom-typescript and when I open a TS file I do get the TypeScript status bar on the bottom that says "Error In Open Files" and "Last Build Output" and such. 

I don't get any autocomplete though. Nothing pops up at all as I type. Nothing pops up when I hover over variables, go to declaration doesn't work, pretty much nothing works except for the status bar.

The status bar does update as I type (mostly just "Js emit is outdated" and "Js emit is up to date").

Initially I did not have any `tsconfig.json` file. I added one to the root with mostly default options and an exclude for node modules. I still had the problem so I replaced the `tsconfig.json` with empty options, `{}`. Still same issue.

What can I look into to resolve what's going on? Seems like it must be something wrong with my setup (I just installed Atom today, was using WebStorm previously).

Thanks,

Sam

`atom-typescript\package.json` snippet (too long to post full file)

```
{
  "name": "atom-typescript",
  "version": "6.0.0",
  "main": "./dist/main/atomts",
  "bin": {
    "atbuild": "./dist/main/bin/atbuild"
  },
  "preferGlobal": "true",
  "description": "The only TypeScript plugin you will ever need.",
  "engines": {
    "atom": ">=0.199.0 <2.0.0",
    "node": "*"
  },
  "providedServices": {
    "autocomplete.provider": {
      "versions": {
        "2.0.0": "provide"
      }
    },
    "linter": {
      "versions": {
        "1.0.0": "provideLinter"
      }
    }
  },
  "consumedServices": {
    "snippets": {
      "versions": {
        "0.1.0": "consumeSnippets"
      }
    }
  },
  ...
  "dependencies": {
    "atom-package-dependencies": "https://github.com/basarat/atom-package-dependencies/archive/cb2.tar.gz",
    "atom-space-pen-views": "^2.0.4",
    "babel": "^5.6.23",
    "basarat-text-buffer": "6.0.0",
    "d3": "^3.5.5",
    "emissary": "^1.3.3",
    "escape-html": "^1.0.1",
    "fuzzaldrin": "^2.1.0",
    "glob-expand": "0.0.2",
    "htmltojsx": "0.2.4",
    "immutable": "^3.7.3",
    "json2dts": "0.0.1",
    "mkdirp": "^0.5.0",
    "ntypescript": "1.201508230720.1",
    "react": "^0.13.3",
    "season": "^5.1.4",
    "strip-bom": "^2.0.0"
  },
  ...
}
```

**Comment by basarat** [comment] 2015-08-31 02:10
> I don't get any autocomplete though. Nothing pops up at all as I type.

Did you get the message : `AtomTS: Dependencies installed correctly. Enjoy TypeScript ♥`  

Ref : https://github.com/TypeStrong/atom-typescript#installation :rose:

**Comment by ggrumbley** [comment] 2015-10-20 15:57
I am having the exact same issue. I installed the typescript package in the manner described on the README but I still have no autocomplete or hover functionality. I did not see the `AtomTS: Dependencies installed correctly. Enjoy TypeScript ♥` message displayed.

**Comment by eliorcohen** [comment] 2015-11-23 13:40
i had the same issue. it's seems to be related with permissions.
the only way i successfully get it to work is to start the atom from the the folder with "sudo" command.

```sudo atom ./``` 

and the autocomplete started to work as expected.

**Comment by laurelnaiad** [comment] 2015-11-27 19:56
Wow, I just realized how much better atom-typescript is when you launch atom with sudo!

Would be nice not to have to do this, though.

**Comment by hitchcockwill** [comment] 2015-12-10 20:29
I'm experiencing this issue as well. I tried installing atom-typescript through the UI then removed it and tried installing through CLI. The CLI install resulted in: ```Installing atom-typescript to /Users/willhitchcock/.atom/packages ✓``` but not the ```AtomTS: Dependencies installed correctly. Enjoy TypeScript ♥``` readout mentioned above. I also tried opening atom with ```sudo atom ./```, no luck there.

**Comment by basarat** [comment] 2015-12-11 03:09
Anyone have any stack trace (open dev tools https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#workflow) :rose:

**Comment by hitchcockwill** [comment] 2015-12-11 14:12
Just installed the development version and rebooted. I'm getting a few errors in the console:

```
Error: Project file contains invalid options
    at Object.getProjectSync (/Users/willhitchcock/Projects/Development/atom-typescript/dist/main/tsconfig/tsconfig.js:260)
    at getOrCreateProjectFile (/Users/willhitchcock/Projects/Development/atom-typescript/dist/main/lang/projectCache.js:74)
    at Object.getOrCreateProject (/Users/willhitchcock/Projects/Development/atom-typescript/dist/main/lang/projectCache.js:141)
    at Object.getCompletionsAtPosition (/Users/willhitchcock/Projects/Development/atom-typescript/dist/main/lang/projectService.js:104)
    at Child.RequesterResponder.processRequest (/Users/willhitchcock/Projects/Development/atom-typescript/dist/worker/lib/workerLib.js:49)
    at process.<anonymous> (/Users/willhitchcock/Projects/Development/atom-typescript/dist/worker/lib/workerLib.js:227)
    at emitTwo (events.js:87)
    at process.emit (events.js:172)
    at handleMessage (internal/child_process.js:685)
    at Pipe.channel.onread (internal/child_process.js:440)
```

and 

```
Uncaught (in promise)

{
  "method": "getOutputJsStatus",
  "message": "Project file contains invalid options",
  "stack": "Error: Project file contains invalid options\n    at Object.getProjectSync (/Users/willhitchcock/Projects/Development/atom-typescript/dist/main/tsconfig/tsconfig.js:260:32)\n    at getOrCreateProjectFile (/Users/willhitchcock/Projects/Development/atom-typescript/dist/main/lang/projectCache.js:74:36)\n    at Object.getOrCreateProject (/Users/willhitchcock/Projects/Development/atom-typescript/dist/main/lang/projectCache.js:141:27)\n    at Object.getOutputJsStatus (/Users/willhitchcock/Projects/Development/atom-typescript/dist/main/lang/projectService.js:602:34)\n    at Child.RequesterResponder.processRequest (/Users/willhitchcock/Projects/Development/atom-typescript/dist/worker/lib/workerLib.js:49:60)\n    at process.<anonymous> (/Users/willhitchcock/Projects/Development/atom-typescript/dist/worker/lib/workerLib.js:227:23)\n    at emitTwo (events.js:87:13)\n    at process.emit (events.js:172:7)\n    at handleMessage (internal/child_process.js:685:10)\n    at Pipe.channel.onread (internal/child_process.js:440:11)",
  "details": {
    "projectFilePath": "/Users/willhitchcock/Projects/Development/proeditors-CustomerUI/tsconfig.json",
    "errorMessage": "Unknown Option: compileOnSave"
  }
}
```

**Comment by basarat** [comment] 2015-12-13 23:30
> I'm seeing this second error message several times with different methods:

@hitchcockwill sorry for the late reply. That is by design. We are just erroring out on invalid projects. We show a message for this as well : 

![image](https://cloud.githubusercontent.com/assets/874898/11770246/637f2828-a24d-11e5-9c82-9baebb15752b.png)

That if you click would guide you to the fix. Basically you have something like : 

```json
{
    "compilerOptions": {
        "compileOnSave": false,
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false
    },
```

When you should have : 
```json
{
    "compileOnSave": false,
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false
    },
```

@hitchcockwill docs : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#options. So that fixes your error :rose:

Anybody else got a stacktrace with a valid error ? : rose: If not I will close this.

**Comment by hitchcockwill** [comment] 2015-12-14 16:11
After making that change in the tsconfig file I started getting autocomplete suggestions as expected in my .ts files. They are pretty slow, but they do work.

**Comment by basarat** [comment] 2015-12-14 22:37
@hitchcockwill check that the tsconfig is not touching all files. See FAQ https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#for-really-large-projects-atom-typescript-gets-slow for details :rose:

We should probably be easily able to figure out the intent and understand that its a folder exclusion ourselves at some point :rose:

**Comment by hitchcockwill** [comment] 2015-12-15 02:05
Thanks @basarat I was having some other issues with the plugin and just discovered that I needed to configure my tsconfig. I've got it set up correctly now and everything seems to be working at lot better.

**Comment by basarat** [comment] 2015-12-15 02:35
Cool. Since no one else has reported back, closing this :rose:

**Closed by basarat** 2015-12-15 02:35 UTC

**Comment by nikhildev** [comment] 2016-05-18 07:24
Hi,

I think the issue still persists. Autocomplete and format was working totally fine for me, until recently. I removed all my plugins except nuclide. Still no go.

However, if I run Atom from the CLI with sudo, things work perfectly fine. Here is a snippet from the console when I try autocomplete without atom started with sudo

```
PARENT ERR: no child when you tried to send : errorsForFile
/Users/nikhildev/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:183 CHILD ERR STDERR: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

/Users/nikhildev/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:196 ts worker restarting. Don't know why it stopped with code: null
```

What might I be missing here?

Thanks

**Comment by canda** [comment] 2016-05-30 06:25
There was no error displayed on atom until I opened the tsconfig.json
Wouldn't it be nice if we show a message to know why the autocomplete isn't working?

**Comment by gurumohanreddy** [comment] 2016-06-26 17:18
For atom-typescript and any new typescript project in general, for things like autocomplete to work correctly, you must have a tsconfig.json file.  atom-typescript has a command to generate you a file, when you're editing a .ts file.

Press Ctrl+Shift+P and type create file and click on the first result from typescript

**Comment by jasoninrapid** [comment] 2016-07-13 17:39
For anyone that stumbles across this on a Google search and is looking for a solution on Windows 7, just give it time.  When I installed and started working on an existing project it took a couple of minutes for Atom to process through a number of items in the status at the bottom.  Once it finally got done with those then my autocomplete and related features started working.

**Comment by AskYous** [comment] 2016-08-20 22:16
I pressed this button and it started working:

![image](https://cloud.githubusercontent.com/assets/791996/17834177/15e316a4-66e9-11e6-97cd-2ec4f4a7cc47.png)

**Comment by jasonmorita** [comment] 2016-10-11 17:29
Make sure you have a `tsconfig.json` either in the root of your project or in the directory in which you are working.

**Comment by 7stud** [comment] 2017-01-14 07:08
I've got a tsconfig.json file in the root of my project directory:

     ~/a2_angular_projects/angular2-get-started

and this is it:

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }
}

and I'm trying to edit files in the directory:

    ~/a2_angular_projects/angular2-get-started/app

First, in the TypeScript area at the bottom of the editor, I see the message:

-tsconfig.json   X JS Outdated 

Sometimes it goes away, and then it just comes back when I open another file.  Saving the file does not get rid of it.

Second, the autocomplete does not work as shown in the demo at:

https://atom.io/packages/atom-typescript

When I type out the same example shown:

    var foo = 123;
    var bar = foo.toString();

I don't see anything popping up.  If I type:

    var bar = foo.

and wait, then after at least 3 seconds and sometimes as long as 6 seconds, an autocomplete menu displays.

If I hover over something, I do see the type.

Macbook Pro
OSX 10.10.5
atom 1.13.0x64

**Comment by amhuhn2** [comment] 2017-03-10 22:46
I wasn't getting any autocomplete at all.  In the status bar, I clicked on "TypeScript", and it brought up a list of all languages supported....I noticed that there were two Typescript in the list.  I clicked on the *other* one (the one that was not currently selected), and voila!  Suddenly I started to get autocomplete functionality.

**Comment by DrCo** [comment] 2017-03-20 18:39
Changing this atom-typescript tsconfig.json worked for me.
Under packages -> atom-typescript -> lib -> tsconfig.json

{

  "compileOnSave": true,

  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "jsx": "react",
    "lib": ["es6", "dom"],
    "module": "commonjs",
    "noLib": false,
    "outDir": "../dist",
    "preserveConstEnums": true,
    "reactNamespace": "dom",
    "skipLibCheck": true,
    "sourceMap": false,
    "strict": true,
    "target": "es6"
  },
}

The "compileOnSave" line should be moved to the top and comma separated, similar to basarat's 2015 fix

**Comment by vedk21** [comment] 2017-06-23 20:55
if anyone still facing this issue please check whether you have installed package `angular-2`. By disabling or uninstalling this may solve your problem. 
cheers.

**Comment by peturh** [comment] 2017-08-30 09:23
@amhuhn2 solutions worked for me!

First in bottem right corner:

![image](https://user-images.githubusercontent.com/3379947/29865337-960e93d6-8d75-11e7-942e-635430fe6670.png)

Then search for TypeScript and choose the one that isn't selected.

![image](https://user-images.githubusercontent.com/3379947/29865311-851267f6-8d75-11e7-9abb-2c090ebbe56a.png)

Works!

**Comment by hardy1334** [comment] 2017-12-03 17:02
I was also facing the similar kind of problem,but I resolved this problem by Installing "TYPESCRIPT PACKAGES" in the atom text editor,  this problem is resolved but it's not highlighting the mistakes in the editor itself.  It's displays errors in the terminal.



![screenshot from 2017-12-03 22-29-33](https://user-images.githubusercontent.com/31733278/33527607-c8eae2d8-d879-11e7-8207-5f8b8f08e62a.png)

**Comment by Devillman** [comment] 2018-01-24 17:39
@amhuhn2  That was the problem for me as well thank you so much it works like a charm now! :)

**Comment by danieldogeanu** [comment] 2018-02-13 09:29
Guys, install `ide-typescript` package in Atom. It will solve all of your problems! The package is made by the guys at Atom, and is still in beta, but it works like a charm.

PS: Just so you know, the current version of Atom uses `language-typescript` and not `atom-typescript`. I don't think `language-typescript` is supposed to have any of those features anyway.
