### ISSUE TITLE
@param and @return not showing up in tooltip documentation

### ISSUE THREAD

**Issue by gajdot** [TypeStrong/atom-typescript#1262] opened 2017-05-19 07:08 UTC
When creating a documentation for TypeScript the tooltip for simple text is showing up as intended, but if I use @params or @return then the line isn't showing up. As soon as I have a @ in the beginning of the comment line, it's not showing up and the param documentation isn't recognized

![57177ba0-363d-11e7-8879-28eac6778f76](https://cloud.githubusercontent.com/assets/8439590/26236821/02a839d0-3c7b-11e7-8e7d-1e25396e9280.png)

Is should show below the main description ever @param and @return description

**Comment by lkloh** [comment] 2017-05-21 00:30
Can I try and fix this one?

**Comment by guncha** [comment] 2017-05-21 16:11
@lkloh, yeah, give it a go. `tooltipManager.ts` is a good starting point. `quickInfo` command returns a few pieces of data and seems like we're just showing the first one.

**Comment by lkloh** [comment] 2017-05-21 22:07
Thanks I'll take a look

**Comment by lkloh** [comment] 2017-05-26 01:58
It seems that the info for params appears when you mouse over the param argument instead. `tooltipManager.ts` calls `quickinfo` in `client.ts` that returns info about the function itself on mouseover, but as far as I can tell there is no protocol that gets info about the params of the function in `client.ts`. Any idea where to look for info about the params of a function when I mouseover the function name?

**Comment by lkloh** [comment] 2017-05-26 01:58
<img width="458" alt="screen shot 2017-05-25 at 9 56 21 pm" src="https://cloud.githubusercontent.com/assets/5299610/26477688/58c344bc-4195-11e7-8c93-b617b5686347.png">

**Comment by guncha** [comment] 2017-05-26 15:00
There is a `signatureHelp` command for `tsserver` that might be what you're looking for. The `tooltipManager` should then check if you're mousing over a function signature (from the `quickInfo` result) and fire this second command to get additional information.

**Comment by skandasoft** [comment] 2018-06-18 23:40
any idea where this is

**Comment by ramtinsoltani** [comment] 2018-08-17 03:06
Any updates on this issue?

**Comment by rohitghy5** [comment] 2019-03-19 02:28
Any updates on this issue? Still the issue is there

**Comment by lierdakil** [comment] 2019-03-22 18:03
Pull requests are welcome. The code responsible is currently in `lib/main/atom-ide/datatipProvider.tsx` for atom-ide-ui tooltips and `lib/main/atom/tooltips/tooltipView.tsx` for builtin tooltips. At least in recent enough TypeScript releases, `QuickInfoResponseBody` has `tags` property that should have some information on jsdoc tags. Should be doable from there.

**Comment by JvPy** [comment] 2019-12-13 03:45
still open? would like to help

**Comment by lierdakil** [comment] 2019-12-13 07:24
I apparently forgot to close this, sorry. This was implemented in #1523, released in 13.4.0

**Closed by lierdakil** 2019-12-13 07:24 UTC
Labels: good first issue, help wanted
