### ISSUE TITLE
 7.6.3 doesn't work es6 target

### ISSUE THREAD

**Issue by arusakov** [TypeStrong/atom-typescript#692] opened 2015-10-29 14:02 UTC
tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es6"
    },
    "filesGlob": [
        "./**/*.+(ts|tsx)",
        "./typings/tsd.d.ts"
    ],
    "files": [
        "./index.ts",
        "./typings/react/react.d.ts",
        "./typings/tsd.d.ts"
    ],
    "exclude": []
}
```
My index.ts:
```typescript
import * as React from 'react';
console.log(React);
```
Build with F6 and index.js:
```javascript
var React = require('react');
console.log(React);
```

**Comment by basarat** [comment] 2015-10-30 07:22
Sorry, you can watch this issue and till it gets resolved lock your atom-typescript to an earlier version. `apm install atom-typescript@versionWhichWorksForYou` :rose: 

Duplicate of https://github.com/Microsoft/TypeScript/issues/5110 and https://github.com/TypeStrong/atom-typescript/issues/643

**Closed** 2015-10-30 21:16 UTC
Labels: bug, waiting:typescript-team

**Comment by basarat** [comment] 2015-10-30 21:21
Fixed : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.7.0
