### ISSUE TITLE
tsconfig.json The project file contains invalid JSON

### ISSUE THREAD

**Issue by ctaggart** [TypeStrong/atom-typescript#465] opened 2015-07-14 17:03 UTC
I was just trying to get started again with Atom TypeScript on an existing TypeScript project. I created a basic `tsconfig.json`, but keep getting an error about `The project file contains invalid JSON`. 

![image](https://cloud.githubusercontent.com/assets/80104/8679387/4379c77e-2a0f-11e5-99d0-13e5033601ac.png)

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "amd",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true
    },
    "filesGlob": [
        "./**/*.ts",
        "!node_modules/**/*.ts"
    ]
}
```

I get the same error with a `tsconfig.json` of
```
{}
```

![image](https://cloud.githubusercontent.com/assets/80104/8679449/97d3057e-2a0f-11e5-99f2-b30fcb7aaf7c.png)

**Comment by basarat** [comment] 2015-07-15 00:25
That JSON is valid. Any errors in the dev console?

**Comment by basarat** [comment] 2015-07-15 00:28
Perhaps you can try doing a `console.error` here : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L341-L346

**Comment by ctaggart** [comment] 2015-07-15 01:45
OK, did that. I edited
![image](https://cloud.githubusercontent.com/assets/80104/8689094/75f1eec2-2a58-11e5-8965-c8990e5202ce.png)

Then inspected with cmd+option+i and got several of these:

![image](https://cloud.githubusercontent.com/assets/80104/8689080/5eeda3d8-2a58-11e5-8760-9fc2b62ef5cb.png)

**Comment by basarat** [comment] 2015-07-15 01:55
Expand `details`

**Comment by basarat** [comment] 2015-07-15 01:56
Sorry I see `Unexpected token ]`. Console.error the `projectFileTextContent` to make sure it matches what you presented here

**Comment by ctaggart** [comment] 2015-07-15 02:43
![image](https://cloud.githubusercontent.com/assets/80104/8689720/53941898-2a60-11e5-9e7d-f191f276ee8a.png)

My current tsconfig.json being:
![image](https://cloud.githubusercontent.com/assets/80104/8689742/a14df892-2a60-11e5-9705-06812ae3e378.png)

**Comment by basarat** [comment] 2015-07-15 03:26
Okay this is *weird*. Can you in the console type in `JSON.parse('{}')` Cause that's whats throwing the exception it seems

**Comment by blakeembrey** [comment] 2015-07-15 03:31
@basarat Just chiming in, but it could be the BOM - you might need to strip it out first.

**Comment by basarat** [comment] 2015-07-15 03:41
> but it could be the BOM. 

Thanks! (I feel like JSON.parse should be okay with that but worth checking) @ctaggart can you see what is mentioned in the status bar if you open the `tsconfig.json` file : 

![image](https://cloud.githubusercontent.com/assets/874898/8690382/30036c20-2af7-11e5-93d1-0747e52025ec.png)

**Comment by blakeembrey** [comment] 2015-07-15 03:44
@basarat `JSON.parse` actually doesn't handle it (`JSON.parse('\ufeff{}')`). Also, `node -p "require.extensions['.json'].toString()"` will show that it also strips the BOM:

```js
function (module, filename) {
  var content = fs.readFileSync(filename, 'utf8');
  try {
    module.exports = JSON.parse(stripBOM(content));
  } catch (err) {
    err.message = filename + ': ' + err.message;
    throw err;
  }
}
```

**Comment by basarat** [comment] 2015-07-15 03:48
@blakeembrey thanks! Will push a fix soon :rose:

**Comment by ctaggart** [comment] 2015-07-15 03:51
I've confirmed that it is the BOM. :+1:

**Comment by basarat** [comment] 2015-07-15 03:56
Thanks @blakeembrey! Fixed with `5.0.28`

**Closed** 2015-07-15 03:55 UTC
Labels: bug

**Comment by ctaggart** [comment] 2015-07-15 04:18
Should JSON files have the BOM or not? This fix strips it off. Visual Studio then detects the file as Codepage 1252 instead of UTF8.

![image](https://cloud.githubusercontent.com/assets/80104/8690796/e2e7beb6-2a6d-11e5-903c-938a227e326b.png)

**Comment by blakeembrey** [comment] 2015-07-15 04:27
@ctaggart It's valid to have it, but it's not required. The patch doesn't look like it's stripping it from the actual file, just from the string before parsing in memory - maybe something else has stripped it from the file? Either way, both encodings should parse the same since your JSON only contains ASCII.

**Comment by basarat** [comment] 2015-07-15 05:04
> This fix strips it off

Not this fix specifically .. but we do rewrite the file if e.g. `files` needs to be updated. That said what we write is *correct raw JSON* so should be okay with other editors.

**Comment by selfrefactor** [comment] 2016-07-01 04:49
i can confirm the bug
