### ISSUE TITLE
How do I get rid of this huge blue tooltip?

### ISSUE THREAD

**Issue by kulikalov** [TypeStrong/atom-typescript#1540] opened 2020-01-20 15:49 UTC
I’ve tried to play around with atom-typescript settings, but no luck. How do I disable this tooltip? https://prnt.sc/qnj9kv

**Comment by lierdakil** [comment] 2020-01-21 09:06
Hi. This is a duplicate of #1483. TL;DR is currently this: you can either hide all builtin tooltips via editing your stylesheet (see https://github.com/TypeStrong/atom-typescript/issues/1483#issuecomment-494543554), or installing atom-ide-ui, and disabling signature tooltips there (or perhaps you'll enjoy their implementation better).

Yes, I know this is long overdue. I'll try to remember to add a flag to disable signature help automatic pop-ups in the next release.

**Comment by lierdakil** [comment] 2020-02-20 13:23
v13.5.0 adds a new configuration option `sigHelpDisplayOnChange` ("Display signature help tooltips on keystroke"), which controls whether signature help is displayed on keystroke (enabled by default).

Even when this option is disabled, one can manually open signature help tooltip with `typescript:show-signature-help` command if desired. It won't show up unprompted though.

**Closed by lierdakil** 2020-02-20 13:23 UTC
Labels: duplicate
