### ISSUE TITLE
Newest version atom does not support your package

### ISSUE THREAD

**Issue by jeffaustin81** [TypeStrong/atom-typescript#584] opened 2015-09-18 03:17 UTC
<img width="1172" alt="screen shot 2015-09-17 at 8 17 09 pm" src="https://cloud.githubusercontent.com/assets/10277396/9951263/1c8b6c4c-5d79-11e5-9baf-2517be696ebc.png">

**Comment by basarat** [comment] 2015-09-18 07:05
duplicate of https://github.com/TypeStrong/atom-typescript/issues/583. Seems mac only bug.

**Comment by basarat** [comment] 2015-09-18 07:05
Feel free to chime in here : https://github.com/TypeStrong/atom-typescript/issues/583#issuecomment-141353810 :rose:

**Closed by basarat** 2015-09-18 07:05 UTC
