### ISSUE TITLE
Angular 2 Inline html template highlight broken after update

### ISSUE THREAD

**Issue by gfauchart** [TypeStrong/atom-typescript#1370] opened 2017-11-02 17:29 UTC
hello 

After upgrading to 11.0.10 this feature doesn't work anymore. if I install 11.0.1 its working fine.
not sure if this is a bug, or this is not supported anymore

**Comment by hotslab** [comment] 2017-11-12 07:47
This is happening to me too. Can this please be resolved?

**Comment by senyaak** [comment] 2017-12-07 20:42
Same problem hier :(

**Comment by HoplaGeiss** [comment] 2017-12-22 14:35
I had the same issue upgrading to 11.0.10. Going back to 11.0.3 fixed the issue.

**Comment by beeman** [comment] 2018-01-11 18:09
Confirmed that this is the fix:
```
$ apm install atom-typescript@11.0.3
```

**Comment by lierdakil** [comment] 2018-01-11 18:20
Since v12, we don't even have our own grammar, instead relying on what [Atom bundles](https://github.com/atom/language-typescript) (because otherwise grammars conflict and there's little reason to create conflicts on default configuration). So closing.

**Closed by lierdakil** 2018-01-11 18:20 UTC
Labels: category:grammar

**Comment by beeman** [comment] 2018-01-11 18:22
@lierdakil any hints on how that can provide the functionality that we're missing?

**Comment by lierdakil** [comment] 2018-01-11 18:35
We weren't responsible for the grammar in the first place anyway. All we did was basically copy-paste https://github.com/Microsoft/TypeScript-TmLanguage. That's literally the same thing that Atom now does. So grammar-related issues should probably go there, and changes will trickle down eventually.

Do check if the problem reproduces with Atom's bundled grammar first though.

Sorry if that's unsatisfactory, but we don't have enough resources to maintain a grammar fork.

**Comment by beeman** [comment] 2018-01-11 19:14
@lierdakil thanks for the response. I'll probably just keep the version pinned and disable `deprecation-cop` for now as I don't have time to search for a fix of a regression :-)

Thanks for the effort of maintaining atom-typescript.

**Comment by beeman** [comment] 2018-10-18 17:52
Thanks @colingm, interesting. Currently not using Atom for any projects, but it's nice to know this is functionality is back 👍
