### ISSUE TITLE
Configure placement of type tooltip.

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/atom-typescript#1462] opened 2018-11-05 19:25 UTC
The type tooltip appears on top of error tooltips:

![screen shot 2018-11-05 at 11 20 59 am](https://user-images.githubusercontent.com/297678/48021421-733c4200-e0ed-11e8-8a1e-7e1d10578754.png)

It would be nice to have it appear on top of the mouse instead of below, or to make it appear below an existing error tip, or perhaps to make the error tip appear above the line.

**Comment by trusktr** [comment] 2018-11-05 19:33
A workaround for now that works most of the time but not always, is to render the error tooltip lower with a CSS transform:

```less
#linter-tooltip {
	transform: translateY(40px);
}
```

![screen shot 2018-11-05 at 11 32 45 am](https://user-images.githubusercontent.com/297678/48021879-87cd0a00-e0ee-11e8-86bc-5c1a195ea69e.png)


but sometimes it fails when the type tip is too tall:

![screen shot 2018-11-05 at 11 33 11 am](https://user-images.githubusercontent.com/297678/48021898-95828f80-e0ee-11e8-82a8-17e9f2240642.png)

**Comment by trusktr** [comment] 2018-11-07 03:50
I also placed made this suggestion for linter-ui-default: https://github.com/steelbrain/linter-ui-default/issues/524

**Comment by lierdakil** [comment] 2018-11-07 23:08
This is basically a duplicate of https://github.com/TypeStrong/atom-typescript/issues/1442. There is no good resolution except for using atom-ide-ui for both type and error tooltips (then atom-ide-ui can sort those out). Which is in the works currently. I'll make a note to make tooltip position a bit more configurable.

**Comment by trusktr** [comment] 2018-11-10 22:37
Check it out, I came up with [some CSS](https://github.com/steelbrain/linter-ui-default/issues/524#issuecomment-437626440) to flip the linter-ui tooltip onto the top of the line so it doesn't conflict with the atom-typescript tip:

<img width="1312" alt="screen shot 2018-11-10 at 2 24 19 pm" src="https://user-images.githubusercontent.com/297678/48306874-23e38080-e4f6-11e8-9924-2d5e43f0f73a.png">
<img width="1170" alt="screen shot 2018-11-10 at 2 33 27 pm" src="https://user-images.githubusercontent.com/297678/48306875-23e38080-e4f6-11e8-91a8-36e723a739ea.png">

**Comment by lierdakil** [comment] 2018-11-18 06:42
Tooltip position (top/bottom) is configurable in v12.7.0. Also, Atom-IDE tooltips are available as an option, so when using Atom-IDE exclusively, you will get proper tooltip spacing.

**Closed by lierdakil** 2018-11-18 06:42 UTC

**Comment by trusktr** [comment] 2018-12-28 05:35
@lierdakil nice, thanks for the feature!
