### ISSUE TITLE
False Linter Errors require close/open files

### ISSUE THREAD

**Issue by ColaColin** [TypeStrong/atom-typescript#1300] opened 2017-07-01 17:47 UTC
I am getting lots of Linter Errors that usually involved extremely distorted code.
For example I write:

`providers: [SalesService]`

and get the error:

"Cannot find name 'SalesServiceecivreSsealS".

If I close and reopen the file in question the error is gone. Pressing F6 for a build tells me "Emit success", but the linter continues to show the errors.

This happens a lot, but not always. Sometimes I can write stuff and it all works. But it also often shows such errors where it seems as if the linter is reading a file that involves random distortion of my actual code.

Running Atom 1.18 and atom-typescript 11.0.5

**Comment by guncha** [comment] 2017-07-02 23:35
I've seem something similar. This is a symptom of `tsserver` view of the file being out of sync with what's in the editor. Because it's likely a race condition somewhere and only happens once in a while, it's going to be very hard to debug.

@ColaColin, when it happens again, it would help if you could paste the source file, the exact error messages (they hint at what the servers idea of the file is) and anything that might be in the developer console of Atom. Even better would be a way to reproduce it, but I'm not hopeful. Meanwhile I'll look at the code to see what could potentially be causing this.

**Comment by ColaColin** [comment] 2017-07-03 01:56
At least yesterday it wasn't just happening "once in a while". It was happening more like 95% of the time. I tried atom restarts and typescript reinstalls.

From the many error messages of this kind I had to see it made the strong impression that it somehow saw keypresses multiple times.

In many cases I'd write "word" and it told me "cannot find wwwwwoooooooorrrrrrrrdddddd".
I assume combined with a little randomness in how often a keypress is registered and backspace presses and maybe copy paste that's what makes it produce those random patterns.

I'll check up on this tomorrow and provide you with the info you need. Unless it magically fixed itself tomorrow similar to the way it magically broke itself I have a setup that seems to cause this all the time.

**Comment by ColaColin** [comment] 2017-07-06 17:28
I am sorry for the late reply, other things had me distracted.

The dev console shows no logs at all.

But I think I have a good hint for you: I know what triggers it to break for me.
I've been working with angular4 and played around with the tutorial project. Then I wanted to start make my actual project so I created another project based on the angular4 starter template. So now I have two angular projects next to each other in my repository. 

Since I wanted to copy over some stuff from the old to the new project I went into the parent directory that contained both of these projects and opened "atom ."
That is what causes the error. I just opened only my new project and everything worked fine. Now I opened the parent folder again and it is broken again.

I've zipped the two projects here they are: http://nanodesu.info/static/salescounter.zip
Unpack in some directory and do "atom ." in it. Hopefully this will cause the error on your end as well.

**Comment by Piorunj** [comment] 2017-07-07 15:23
I get the same error on my own project, even if it's the only one open. 

As you can see on the screen bellow, the error message doesn't correspond to the editor content. (before writing this line there was no error)

![image](https://user-images.githubusercontent.com/14125122/27964490-bcbdaae2-6338-11e7-951a-7f35dda9b8d3.png)

**Comment by runartrollet** [comment] 2017-07-07 17:00
I think I got a consistant way of reproducing this error. Open the save `.ts`-file in two panes and have them side-by-side. After just a few edits, this error shows up.

**Comment by guncha** [comment] 2017-07-07 17:23
You know what, that explains the errors - multiple keystrokes are recorded where there should only be one. Multiple TypescriptBuffers are listening for the same changes. This should be an easy fix.

**Comment by paulblyth** [comment] 2017-08-08 07:49
I have this problem too - I didn't even realise the file was open in two panes!

**Comment by ColCh** [comment] 2017-09-05 13:14
Facing this error every day, I'm tired of that. No PR?

@guncha please, can you inform a place to start a fix?

**Comment by runartrollet** [comment] 2017-09-06 08:02
I recently updated my typescript-version to the nightly version 2.6, which seem to make the problem appear even when there is only one pane open of a single file. Not sure yet if this is related.

**Comment by demisx** [comment] 2017-09-21 04:09
I am on the latest Atom and `atom-typescript` and I have to constantly close and reopen files for these false errors to go away. Very annoying.

**Comment by brucemackenzie** [comment] 2017-09-27 16:31
I also see this every day. It slows me down when everything is red and I have to re-open the file to find out if there are any actual errors.

**Comment by brucemackenzie** [comment] 2017-09-27 16:33
<img width="749" alt="stale linter error" src="https://user-images.githubusercontent.com/3074131/30925477-da0aab18-a366-11e7-8f83-625cbcb5381e.png">

This was an error during typing, but is no longer an error. After I correct it, the linter should make it go away right?

**Comment by brucemackenzie** [comment] 2017-09-27 16:39
Re-reading the thread, i noticed a request to try to reproduce in Developer Mode.
That fixes it!

**Comment by demisx** [comment] 2017-09-27 18:26
@brucemackenzie I am sorry, if I am misreading this. What exactly fixed this problem for you because we deal with this nuisance daily on latest Atom and atom-typescript? Really slows down development, so we would love to know what the fix is. Thank you.

**Comment by brucemackenzie** [comment] 2017-09-28 03:25
The way I _solved_ the problem was to launch Atom in developer mode.
`View` -> `Developer` -> `Open in dev mode...`

**Comment by demisx** [comment] 2017-09-28 15:57
Thanks @brucemackenzie. I see what you mean. I've started entire atom in dev mode via `atom --dev .` and tried to use it that way. Still, as soon as I've opened the second pane, I've got these strange errors showing up again (see attached screenshots). Once I've closed the second pane and reopened the file in one single pane, the errors were gone.

![screen shot 2017-09-28 at 8 45 36 am](https://user-images.githubusercontent.com/4452412/30976886-d7a1ba3c-a42a-11e7-8844-3f31e3544999.jpg)

![screen shot 2017-09-28 at 8 46 39 am](https://user-images.githubusercontent.com/4452412/30976899-dfbd352a-a42a-11e7-8b73-6e730ba0913e.jpg)

**Comment by ColaColin** [comment] 2017-10-05 15:31
Also still suffering from this issue. Any hints where in the code of the plugin this would need to be fixed?

**Comment by demisx** [comment] 2017-10-05 15:32
Not anymore. I've switched to VS Code and forgot about all this. It's like Atom, but without all these annoying bugs.

**Comment by brucemackenzie** [comment] 2017-10-26 15:53
Sadly developer mode no longer fixes this.
I'll try switching entirely to VS.Code (I already use it for node debugging because i couldn't get debugging to work in atom).

**Comment by kubakrzempek** [comment] 2017-11-10 11:19
There is also an alternative in Atom - https://ide.atom.io

**Comment by theGABS** [comment] 2018-01-09 10:06
Still, have this error. 

WTF???!!! Why it is not been fixing yet??

**Comment by kubakrzempek** [comment] 2018-01-10 13:17
@theGABS hey, it is an open source project you can use for free. If you demand something, pay for or work on it. :|

**Comment by demisx** [comment] 2018-01-10 16:08
@theGABS Another great alternative is a free open source editor https://code.visualstudio.com/. Solves many problems we've previously run into in Atom. Git it a try.

**Comment by lierdakil** [comment] 2018-01-11 20:42
Some work towards fixing this is done in v12.0.0. In particular, having two panes with the same file shouldn't trigger this problem anymore.

I'm going to close this. If you run into similar problems post-v12, please open new issues, preferably with reproduction guides.

Thank you for your patience.

**Closed by lierdakil** 2018-01-11 20:42 UTC
