### ISSUE TITLE
Do not trigger autocomplete-plus when it's not typing when using enter for selecting.

### ISSUE THREAD

**Issue by vilic** [TypeStrong/atom-typescript#255] opened 2015-04-13 03:49 UTC
![image](https://cloud.githubusercontent.com/assets/970430/7109572/1a51639a-e1d3-11e4-82d0-900196e6690c.png)

Or if I press enter for new line here, it completes "value".

**Comment by basarat** [comment] 2015-04-13 04:54
Thanks for reporting :heart:  Known issue. Duplicate of : https://github.com/TypeStrong/atom-typescript/issues/255

Workaround : don't map `enter` to autocomplete plus submit. The default is only that `tab` is mapped. You must have set it explicitly.  

Note: this is how autocomplete-plus is designed, provide suggestions as aggressively as it can.

**Closed by basarat** 2015-04-13 04:54 UTC
Labels: duplicate

**Comment by vilic** [comment] 2015-04-16 15:47
Hmm, this issue is #255 and it can't be a duplicate of itself, LOL...

I looked at the GIF demo from autocomplete-plus, but it seems that it's not that aggressive as it is in TypeScript files. I believe maybe it's atom-typescript triggering it too much? https://atom.io/packages/autocomplete-plus 

Also my workmates are complaining about the enter key issue as most of them are used to entering for completion.

It would be great if there was an option to make auto complete for TypeScript less aggressive (align with default behavior of autocomplete-plus).

Thanks for your great work.

**Comment by basarat** [comment] 2015-04-16 21:38
Sorry. Duplicate of https://github.com/TypeStrong/atom-typescript/issues/141 🌹
