### ISSUE TITLE
Not working from clean install?

### ISSUE THREAD

**Issue by jvilk** [TypeStrong/atom-typescript#146] opened 2015-03-04 23:02 UTC
From a clean install of OS X, I installed Node v0.12, Atom, atom-typescript, and autocomplete plus. I made sure all of them are completely updated to their latest versions. I also restarted Atom after it prompted me to, following the atom-typescript installation.

However, atom-typescript refuses to:

* Build typescript files I have open in Atom, even when I force it with cmd+shift+b.
* Provide autocomplete suggestions.

Is there any way to debug why atom-typescript isn't doing anything? Is there a prerequisite piece of software that I might be missing?

**Comment by jvilk** [comment] 2015-03-04 23:10
I figured it out. My project does not have a `tsconfig.json` file, and for some reason some tool I invoked at one point generated an invalid one. 

Thus, this is related to #138. Maybe when you are working on a file *not* mentioned in a `tsconfig.json` in a parent directory, then you don't use that `tsconfig.json`?

**Comment by basarat** [comment] 2015-03-05 01:22
> Is there any way to debug why atom-typescript isn't doing anything

some tips https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#workflow

> Maybe when you are working on a file not mentioned in a tsconfig.json in a parent directory, then you don't use that tsconfig.json?

duplicate of https://github.com/TypeStrong/atom-typescript/issues/45 its not a high priority task as it is really an error on the users behalf

**Closed** 2015-03-05 01:23 UTC
Labels: duplicate
