### ISSUE TITLE
HTMLElement.rootElement is deprecated (Atom 1.19.0-beta0)

### ISSUE THREAD

**Issue by nrozic** [TypeStrong/atom-typescript#1275] opened 2017-06-16 07:37 UTC
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `rootElement` and access
the editor contents directly instead.
```
HTMLElement.rootElement (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:23:10)
getFromShadowDom (/Users/nikola/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:18:19)
Object.attach (/Users/nikola/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:38:18)
TypescriptEditorPane.setupTooltipView (/Users/nikola/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:176:24)
new TypescriptEditorPane (/Users/nikola/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:129:14)
subscriptions.add.atom.workspace.observeTextEditors (/Users/nikola/.atom/packages/atom-typescript/dist/main/atomts.js:85:24)
```

**Comment by Positive07** [comment] 2017-06-17 20:49
Duplicate of #1274 please check if the issue already exists before reporting

**Comment by jcardenasp** [comment] 2017-08-09 15:30
Hello, everyone

I have the same issue with the last update of Atom
![issue_atom](https://user-images.githubusercontent.com/29614769/29129823-af173bf0-7ced-11e7-9062-223efce1f4ec.png)

**Comment by Positive07** [comment] 2017-08-09 15:51
Wow! Sorry I have a PR in progress, I'll finish it today and see if it gets merged

PS: I though this would have been fixed by now 😞

**Comment by jcardenasp** [comment] 2017-08-09 20:32
Don't worry, but thank you so much for your help with this issue, I'm QA engineer automation and Atom is for me the best text editor for my work.

**Comment by ElecTreeFrying** [comment] 2017-08-11 09:47
Same issue 

![as](https://user-images.githubusercontent.com/19801459/29208508-f8ab357a-7ebc-11e7-99ef-6a92589d254e.PNG)

@jcardenasp did you fixed this already?

**Comment by kerabromsmu** [comment] 2017-09-19 14:12
Still having the same issue.

**Comment by lierdakil** [comment] 2017-09-20 08:24
@kerabromsmu, 1. update Atom 2. Update atom-typescript

There's literally no mention of rootElement in the code base since v11.0.7.

**Closed by lierdakil** 2017-09-20 08:24 UTC

**Comment by kerabromsmu** [comment] 2017-09-21 16:17
![atomdeprecation](https://user-images.githubusercontent.com/7052392/30706617-2b914b76-9ef9-11e7-9061-975fb9eb0e60.jpeg)
