### ISSUE TITLE
tsserver crashes with "heap out of memory"

### ISSUE THREAD

**Issue by Xapphire13** [TypeStrong/atom-typescript#1309] opened 2017-07-10 22:43 UTC
tsserver keeps crashing on my machine when I notice there are a large number of static analysis tasks running (the count in the bottom right of the task bar).

This is the error:

> Last output from tsserver:
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
>  
> Error: exited with code: 3
>     at ChildProcess.exitHandler (C:\Users\\******\\.atom\packages\atom-typescript\dist\client\client.js:175:58)
>     at ChildProcess.g (events.js:286:16)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

In addition to this, the TypeScript atom plugin doesn't restart the server when it needs to:
![image](https://user-images.githubusercontent.com/3392349/28043349-5b296adc-6586-11e7-93ba-3ea75f39bb81.png)

This leads to my needing to restart atom.

**Package version**: 11.0.6
**Atom**: 1.18.0 x64
**OS**: Win 10 x64

**Comment by ZuBB** [comment] 2017-09-14 11:36
@guncha @lierdakil imo this is a duplicate of https://github.com/TypeStrong/atom-typescript/issues/1255

**Comment by lierdakil** [comment] 2018-01-11 20:34
Seems like it. Closing as duplicate of #1255. Feel free to yell at me if you think I'm wrong.

Basically, the resolution of all 'out of memory'-type errors seems to boil down to https://sandersn.github.io/manual/Workarounds-for-Out-of-Memory-Crashes.html, and if that doesn't help, file an issue on https://github.com/Microsoft/TypeScript

**Closed by lierdakil** 2018-01-11 20:34 UTC
