### ISSUE TITLE
Uncaught TypeError: Promise.defer is not a function

### ISSUE THREAD

**Issue by NoctisHsu** [TypeStrong/atom-typescript#709] opened 2015-11-09 04:18 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v7.7.2

### Stack Trace

Uncaught TypeError: Promise.defer is not a function

```
At /Users/noctis/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:33

TypeError: Promise.defer is not a function
  at Parent.RequesterResponder.sendToIpcHeart (/Users/noctis/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:33:33)
  at Object.getProjectFileDetails (/Users/noctis/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:106:47)
  at /Users/noctis/.atom/packages/atom-typescript/dist/main/atomts.js:50:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:247:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:311:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:305:19)
  at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:276:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:386:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:448:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  2x -1:03.5.0 editor:auto-indent (atom-text-editor.editor.mini)
     -0:33 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-nucleus-dark-ui)
 45x -0:29.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  5x -0:21.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:18.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:18.6.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.mini.is-focused)
     -0:18.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18.4.0 tool-panel:unfocus (button.btn.btn-default.tool-bar-btn.ion.ion-navicon-round)
```

### Config

```json
{
  "core": {
    "projectHome": "/Work/Projects/",
    "disabledPackages": [
      "file-type-icons",
      "tree-view-breadcrumb",
      "language-typescript",
      "filetype-color",
      "compare-files",
      "compare-files",
      "atom-ternjs",
      "git-history",
      "jsformat"
    ],
    "themes": [
      "nucleus-dark-ui",
      "one-dark-syntax"
    ]
  },
  "atom-typescript": {
    "disableCompileOnSave": false,
    "compileOnSave": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs, v0.3.3
atom-beautify, v0.28.17
atom-jshint, v2.0.0
atom-tsd, v0.9.0
atom-typescript, v7.7.2
atom-yeoman, v0.3.15
autoclose-html, v0.19.0
bottom-dock, v0.3.5
build, v0.48.0
build-grunt, v0.2.0
build-gulp, v0.2.0
color-picker, v2.0.13
compass, v0.9.1
css-comb, v2.4.0
css-snippets, v0.9.0
cucumber, v0.5.0
emmet, v2.3.14
file-icons, v1.6.11
flex-tool-bar, v0.6.0
git-diff-details, v0.21.0
git-log, v0.4.1
gulp-manager, v0.2.13
javascript-snippets, v1.0.0
jshint, v1.8.3
json-schema, v0.1.15
language-SCSS, v0.4.0
language-cshtml, v0.1.1
language-sln, v0.1.0
linter, v1.10.0
local-history, v3.2.3
minimap, v4.16.0
minimap-autohide, v0.10.1
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
nucleus-dark-ui, v0.6.7
omnisharp-atom, v0.25.10
pigments, v0.18.1
project-manager, v2.6.5
project-view, v0.2.0
terminal-panel, v1.14.1
tool-bar, v0.1.9
tool-bar-almighty, v0.2.2
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by basarat** [comment] 2015-11-09 04:39
But it is a function ... 

![image](https://cloud.githubusercontent.com/assets/874898/11026003/7b4f0930-86f7-11e5-8af9-02b038c9eebd.png)

can you open your dev console in atom and type in `Promise.defer` to confirm :rose: It's provided by v8 (node and chrome)

![image](https://cloud.githubusercontent.com/assets/874898/11026048/1a875c50-86f8-11e5-83be-24db0014a1bb.png)

**Comment by NoctisHsu** [comment] 2015-11-09 18:06
![image 2015-11-10 at 2 05 41](https://cloud.githubusercontent.com/assets/1920503/11041990/9e7c2430-874f-11e5-8ad0-722d3e755d2c.png)

the error in console

**Comment by NoctisHsu** [comment] 2015-11-09 18:15
![image 2015-11-10 at 2 05 41](https://cloud.githubusercontent.com/assets/1920503/11042189/b27fd5c0-8750-11e5-9c8f-fbdd9551ee14.png)

the promise function is define at there , but it is not contain defer() :(

**Comment by blakeembrey** [comment] 2015-11-09 18:38
@NoctisHsu The issue is some other package is overriding the `Promise` library built into node. I'd check where that's coming from, and open an issue there.

@basarat `Promise.defer` isn't part of the A+ spec either, is it possible to avoid it?

**Comment by NoctisHsu** [comment] 2015-11-09 18:51
@blakeembrey You are right! The promise function is overridden by 'advanced-open-file' package.
When I remove it ,atom-typescript is working fine.

**Comment by basarat** [comment] 2015-11-09 23:00
> is it possible to avoid it?

@blakeembrey I was lazy. Feel free to create an issue and mark it as up for grabs :rose: 

@NoctisHsu Cheers :rose: Closing as the issue is not in this package.

**Closed by basarat** 2015-11-09 23:00 UTC
Labels: status:needs-more-info
