### ISSUE TITLE
exclude in tsconfig.json doesn't work

### ISSUE THREAD

**Issue by slikts** [TypeStrong/atom-typescript#593] opened 2015-09-20 22:09 UTC
Adding a directory to the exclude section in tsconfig.json doesn't stop atom-typescript from generating errors about .ts files not being included in the compilation context. The files are supposed to be excluded, so the errors are incorrect.

**Comment by basarat** [comment] 2015-09-21 01:08
Up for grabs

# Implementor guidance 

Source code needs to go here : [tsconfig.ts](https://github.com/TypeStrong/atom-typescript/blob/1f516fd2061fe2e6dcaea4fbc560024fdd35121d/lib/main/tsconfig/tsconfig.ts)

For guidance one can use the work done [here](https://github.com/TypeStrong/tsconfig/blob/be5007c5505f73810c6510ecbdc166bed4dfe036/src/tsconfig.ts) basically add the excludes to the pseudo filesGlob.

**Comment by slikts** [comment] 2015-09-21 10:15
The error isn't affected by excluding the file. It's checks for `Project.prototype.includesSourceFile` and displays the error if it doesn't. The fix would be for `includesSourceFile` to check if the file isn't in an excluded directory, but a better fix would be just to remove the error. It's a feature that doesn't play nice with other things, such as using a test runner that supports TS.

**Comment by slikts** [comment] 2015-09-21 12:06
Also, there could be an option to suppress the error. Currently, there is no way to get rid of it other than adding every .ts file to the project. "Helpful" features like this that are implemented in an unintelligent way are quite annoying.

**Comment by basarat** [comment] 2015-09-22 00:47
Sorry I thought you meant : https://github.com/TypeStrong/atom-typescript/issues/377 

On second read this is a duplicate of : https://github.com/TypeStrong/atom-typescript/issues/558

@slikts the fact is that we don't support *lose .ts files*, i.e. files that don't have a tsconfig.json associated. So the error *could be replaced with another* but it would still be an error. Feel free to continue the discussion here : https://github.com/TypeStrong/atom-typescript/issues/558 :rose:

**Closed by basarat** 2015-09-22 00:47 UTC
Labels: bug, category:tsconfig, up-for-grabs

**Comment by Zorgatone** [comment] 2015-09-27 09:54
My files still get compiled even if excluded :disappointed:

**Comment by basarat** [comment] 2015-09-27 23:32
> My files still get compiled even if excluded

@Zorgatone if you are using the `exclude` property, that isn't supported yet : https://github.com/TypeStrong/atom-typescript/issues/377 

You can use `filesGlob` in the meantime https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#filesglob

**Comment by jokerosky** [comment] 2016-04-08 16:03
And it stil doesn`t work in Version 1.8.9 ?
