### ISSUE TITLE
Function as parameter with empty parameter list breaks syntax highlighting

### ISSUE THREAD

**Issue by alisd23** [TypeStrong/atom-typescript#636] opened 2015-10-02 13:42 UTC
When defining a function as a parameter of another function with a signature of
`() => returntype` - (no parameters), the syntax highlighting breaks for the rest of the file

With no parameters:
![image](https://cloud.githubusercontent.com/assets/5804010/10247836/aaaaea2a-6913-11e5-9a30-2758b8392bee.png)

With a single parameter:
![image](https://cloud.githubusercontent.com/assets/5804010/10247854/c2b0d256-6913-11e5-9dba-ae7c7318959c.png)

**Comment by sgal** [comment] 2015-10-02 13:44
It is probably a duplicate of #611. There's a discussion in atom/first-mate repo about it.

**Comment by basarat** [comment] 2015-10-05 04:32
Fixed with #611

**Closed by basarat** 2015-10-05 04:32 UTC
