### ISSUE TITLE
1.Snippets dialog unexpected interaction, 2. Double file path url

### ISSUE THREAD

**Issue by kyle-so-sexy** [TypeStrong/atom-typescript#496] opened 2015-07-27 05:54 UTC
Not exactly sure where to ask this, not particularly sure if this is an issue too.

1. Snippets do not work way it is supposed to be used, with atom-typescript plugin. Description: snippets do not pop-up, while I type them. Instead I have to ctrl+shift+s and that retrieves me a dialog box for snippets, where I again have to type the snippet I want, or am trying to remember.

2. Opening files using, goto declaration, opens the wrong file path. I am using network share samba, and have mapped ip to drive v. And when using goto declaration, it will open a file path of example ip: 10.1.2.3, \\10.1.2.3\folder\file.ts\\10.1.2.3\folder\file.ts

3. Same as 2, for other functionality that requires a file to be opened by the plugin.

if anyone could help me out with question 1, it will be much appreciated! I would help to help out too, but, my knowledge of atom plugins, creation and modification is, rather weak at the moment, JavaScript included.

PS. Thanks for the great plugin!

**Comment by basarat** [comment] 2015-07-27 09:38
> if anyone could help me out with question 1, it will be much appreciated

Screen: 

![asdf](https://cloud.githubusercontent.com/assets/874898/8902788/d1593a34-3496-11e5-8d15-fa293ca392f5.gif)

Is this not the behavior you are getting? Or did you expect something else.

Worth mentioning : https://github.com/atom/autocomplete-snippets/issues/46 :rose:

**Comment by kyle-so-sexy** [comment] 2015-07-27 13:07
That is the behavior, for "default package snippets" (not sure if I'm using the correct wordings) but not for snippets in the snippet.cson, what I have found from following your link is https://github.com/TypeStrong/atom-typescript/issues/433 which would be the most accurate, in that a snippet "works", but it does not display and I must manually press escape then, tab. While that is great, it works, its not a particular fix for me, because I can't remember half the prefixes of the snippets, I usually randomly type out gibberish, and the snippet that pops up is usually closely related, and that's what I use.

Are you fixing it in https://github.com/atom/autocomplete-snippets/issues/46 ? It seems like, mine is a double post of it?

**Comment by basarat** [comment] 2015-07-27 23:33
Short version duplicate of : https://github.com/atom/autocomplete-snippets/issues/46 

> which would be the most accurate, in that a snippet "works", but it does not display

Does not display in general is the bug https://github.com/atom/autocomplete-snippets/issues/46 We have workaround that allows you to use snippets that are shipped as a part of atom-typescript but even in that it only displays if you type in the complete prefix. There is no desire to improve this as really issue `46` is where any further effort should go. 

> Are you fixing it in

No. Its open for a hero. 

Feel free to ask other questions. Closing to keep queue clear :rose:

**Closed by basarat** 2015-07-27 23:33 UTC
Labels: question
