### ISSUE TITLE
[Feature request] Add signature help

### ISSUE THREAD

**Issue by InExtremaRes** [TypeStrong/atom-typescript#1421] opened 2018-04-25 10:12 UTC
Is there a possibility of adding a signature help, so when you are calling a function (constructor, whatever) have a tooltip showing parameters name and type? It is very useful when calling a function with lots of arguments.

atom-ide-ui has this feature so, for instance, ide-typescript can use it directly. I don't know how much this package can (wants) use atom-ide-ui services or if is there any reason to do so.

![image](https://user-images.githubusercontent.com/1635491/39239689-04c1bec8-4858-11e8-84c9-39a22ced548f.png)

**Comment by lierdakil** [comment] 2018-04-25 10:27
Should be possible I think? 
There's a [`signatureHelp` command in tsserver]https://github.com/Microsoft/TypeScript/blob/1f59e6f77a4df9196f83a7ece856cc6d9e0d5467/lib/protocol.d.ts#L1550), and [atom-ide-ui `SignatureProvider` interface](https://github.com/facebook-atom/atom-ide-ui/blob/c3a08f5ade3477e5642c7c5e231cd85551252e98/modules/atom-ide-ui/pkg/atom-ide-signature-help/lib/types.js#L30) seems reasonable

**Comment by InExtremaRes** [comment] 2018-04-25 10:46
Is any plans to _integrate_ more (in whichever sense of the word) this package with atom-ide-ui?

**Comment by lierdakil** [comment] 2018-04-25 22:05
There are no *plans*, but I don't see why not use a readily-available solution instead of inventing our own.

**Comment by InExtremaRes** [comment] 2018-04-25 22:40
Yes of course, just out of curiosity... and well, atom-ide-ui has a lots of services already there.

The only trade off I can think is the very different looks of those tooltips. Maybe more info could be ported as well (quickinfo, etc), but you know, it is just a bagatelle.

**Comment by lierdakil** [comment] 2018-04-25 23:16
> Maybe more info could be ported as well

I don't mind, although not everybody likes atom-ide-ui, so probably a good idea to leave an "escape hatch" in, so to speak.

**Comment by Xapphire13** [comment] 2018-05-24 07:07
Seems this is either a dupe of, or related to #608

**Closed** 2018-11-18 04:02 UTC
Labels: enhancement
