### ISSUE TITLE
problem about TS parsing

### ISSUE THREAD

**Issue by taejin-kim** [TypeStrong/atom-typescript#630] opened 2015-09-30 00:50 UTC
![033](https://cloud.githubusercontent.com/assets/8894265/10181731/c79061ce-6756-11e5-8e12-99b8a7da526e.png)
![034](https://cloud.githubusercontent.com/assets/8894265/10181756/00e6d4ee-6757-11e5-83f6-42fd2040a651.png)

**Comment by basarat** [comment] 2015-09-30 01:36
Duplicate of https://github.com/TypeStrong/atom-typescript/issues/611

Happen with atom update `1.0.15` : https://github.com/atom/first-mate/issues/62

**Comment by taejin-kim** [comment] 2015-09-30 02:52
my current atom version 1.0.19

go to downgrade 1.0.15?

2015-09-30 10:36 GMT+09:00 Basarat Ali Syed <notifications@github.com>:

**Comment by basarat** [comment] 2015-10-04 04:56
Please try https://github.com/TypeStrong/atom-typescript/releases/tag/v7.1.0 :rose:

**Closed by basarat** 2015-10-04 04:56 UTC
Labels: category:grammar, duplicate

**Comment by taejin-kim** [comment] 2015-10-04 05:01
Good!
Thank you so much~
Have a good day!
2015. 10. 4. 오후 1:56에 "Basarat Ali Syed" <notifications@github.com>님이 작성:
