### ISSUE TITLE
Packages Compilation Error

### ISSUE THREAD

**Issue by FernandoFranco** [TypeStrong/atom-typescript#588] opened 2015-09-18 19:15 UTC
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mac_115/.atom/.apm/.apmrc" "--userconfig" "/Users/mac_115/.atom/.apmrc" "rebuild" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fsevents@0.3.5 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fsevents@0.3.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fsevents package,

**Comment by rcchen** [comment] 2015-09-18 21:12
Duplicate of #583

**Comment by basarat** [comment] 2015-09-19 05:35
Fixed with `6.0.12` :rose:

**Closed by basarat** 2015-09-19 05:35 UTC
