### ISSUE TITLE
Highlight breaks on long lines

### ISSUE THREAD

**Issue by shadeglare** [TypeStrong/atom-typescript#669] opened 2015-10-18 18:22 UTC
I noticed that highlight is broken for some "long expression" cases.

Example:
```ts
export type Func16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TOut> = (arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16) => TOut;
```
or a screenshot:
<img width="1035" alt="screen shot 2015-10-18 at 9 17 47 pm" src="https://github-cloud.s3.amazonaws.com/assets/995484/10565626/daaf3b00-75dd-11e5-8c4f-0aba04a7fcc4.png">

**Comment by basarat** [comment] 2015-10-18 23:35
duplicate of https://github.com/TypeStrong/atom-typescript/issues/623 

Atom issue, see : https://github.com/atom/atom/issues/1667 (my comment https://github.com/TypeStrong/atom-typescript/issues/623#issuecomment-143940188) Cheers :rose:

**Closed by basarat** 2015-10-18 23:35 UTC
Labels: category:atom-issue, category:grammar, duplicate
